### ISSUE TITLE
Incorrect link on burgershot.gg

### ISSUE THREAD

**Issue by dennorske** [KaizerHind/VisualTexture_Pawn_SA-MP#1]
Hi!

Great effort making this.
Just letting you know that the link here: https://www.burgershot.gg/showthread.php?tid=518
is dead, and needs to be updated.

Best regards

**Comment by Kaizerhind** [comment]
> Hi!
> 
> Great effort making this.
> Just letting you know that the link here: https://www.burgershot.gg/showthread.php?tid=518
> is dead, and needs to be updated.
> 
> Best regards

Hi, thanks, solved.
